AWSTemplateFormatVersion: "2010-09-09"
Description: |
  AWS resources for Terraform access
Parameters:
  Prefix:
    Type: String
    Description: The prefix for AWS resource names
  RoleArns:
    Type: String
    Description: The ARNs of the roles that the group can assume

Resources:
  TfAccessGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: !Sub ${Prefix}-users

  TfManagedAccountsExecPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub ${Prefix}-policy
      Groups:
        - !Ref TfAccessGroup
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          Effect: Allow
          Action:
            - sts:AssumeRole
          Resource: !Split [",", !Ref RoleArns]

Outputs:
  TfAccessGroup:
    Value: !Ref TfAccessGroup
