---
- name: Deploy CloudFormation for Terraform execution
  hosts: localhost
  vars_prompt:
    - name: managing_account_id
      prompt: Specify the AWS account number for the role
      private: no
    - name: org_prefix
      prompt: Specify the namespace
      private: no
    - name: stack_prefix
      prompt: Specify the prefix for the stacks
      private: no

  tasks:
    - name: Stack for IAM role to run Terraform
      amazon.aws.cloudformation:
        stack_name: "{{ org_prefix }}-{{ stack_prefix }}-role"
        region: us-east-1
        state: "present"
        template: "../cloudformation/admin-account/tf-exec/cfn-tf-exec-role.yml"
        template_parameters:
          ManagedPolicyName: AdministratorAccess
          ManagingAccountID: "{{ managing_account_id }}"
          Prefix: "{{ org_prefix }}-{{ stack_prefix }}"
        termination_protection: yes
        tags:
          "sje:source": ansible
          "sje:namespace": "{{ org_prefix }}"
          "sje:prefix": "{{ stack_prefix }}"
