---
- name: Deploy CloudFormation for Terraform execution
  hosts: localhost
  vars_prompt:
    - name: managing_account_id
      prompt: Specify the AWS account number for the role
      private: no
    - name: org_prefix
      prompt: Specify the namespace
      private: no
    - name: stack_prefix
      prompt: Specify the prefix for the stacks
      private: no
  vars:
    stack_tags:
      - key: "{{ org_prefix }}:source"
        value: ansible
      - key: "{{ org_prefix }}:namespace"
        value: "{{ org_prefix }}"
      - key: "{{ org_prefix }}:prefix"
        value: "{{ stack_prefix }}"

  tasks:
    - name: Stack for IAM role to run Terraform
      amazon.aws.cloudformation:
        stack_name: "{{ org_prefix }}-{{ stack_prefix }}-role"
        region: us-east-1
        state: "present"
        template: "../cloudformation/managing-account/tf-exec/cfn-tf-exec-role.yml"
        template_parameters:
          ManagedPolicyName: AdministratorAccess
          ManagingAccountID: "{{ managing_account_id }}"
          Prefix: "{{ org_prefix }}-{{ stack_prefix }}"
        termination_protection: yes
        tags: "{{ stack_tags | items2dict }}"
