---
- name: Deploy CloudFormation for access to Terraform backend
  hosts: localhost
  vars_prompt:
    - name: managing_account_id
      prompt: Specify the AWS account number for the role
      private: false
    - name: org_prefix
      prompt: Specify the namespace
      private: false
    - name: stack_prefix
      prompt: Specify the prefix for the stacks
      private: false
    - name: kms_key_arn
      prompt: Specify the ARN of the KMS key for the Terraform state
      private: false
    - name: s3_bucket_arn
      prompt: Specify the ARN of the S3 bucket for the Terraform state
      private: false
    - name: ddb_table_arn
      prompt: Specify the ARN of the DynamoDB table for Terraform locking
      private: false
  vars:
    stack_tags:
      - key: "{{ org_prefix }}:source"
        value: ansible
      - key: "{{ org_prefix }}:namespace"
        value: "{{ org_prefix }}"
      - key: "{{ org_prefix }}:prefix"
        value: "{{ stack_prefix }}"

  tasks:
    - name: Stack for IAM role to access Terraform backend
      amazon.aws.cloudformation:
        stack_name: "{{ org_prefix }}-{{ stack_prefix }}-tf-backend-access-role"
        region: us-east-1
        state: "present"
        template: "../cloudformation/managing-account/tf-backend-access/cfn-tf-backend-role.yml"
        template_parameters:
          ManagingAccountID: "{{ managing_account_id }}"
          Prefix: "{{ org_prefix }}-{{ stack_prefix }}"
          TfKmsBackendKeyArn: "{{ kms_key_arn }}"
          TfS3StorageArn: "{{ s3_bucket_arn }}"
          TfDdbLockingArn: "{{ ddb_table_arn }}"
        termination_protection: true
        tags: "{{ stack_tags | items2dict }}"
