---
- name: Deploy CloudFormation for automated Terraform access
  hosts: localhost
  vars_prompt:
    - name: managing_account_id
      prompt: Specify the AWS account number for the role
      private: no
    - name: org_prefix
      prompt: Specify the namespace
      private: no
    - name: stack_prefix
      prompt: Specify the prefix for the stacks
      private: no
    - name: backend_access_role
      prompt: Specify the ARN of the role for accessing the Terraform backend
      private: no
    - name: same_account_exec_role
      prompt: Specify the ARN of the role for running Terraform in the same AWS account
      private: no
    - name: account_0001_exec_role
      prompt: Specify the ARN of the role for running Terraform in another AWS account
      private: no

  tasks:
    - name: Stack for IAM group to use Terraform
      register: iam_group
      amazon.aws.cloudformation:
        stack_name: "{{ org_prefix }}-{{ stack_prefix }}-group"
        region: us-east-1
        state: "present"
        template: "../cloudformation/managing-account/tf-identity/cfn-tf-access-group.yml"
        template_parameters:
          Prefix: "{{ org_prefix }}-{{ stack_prefix }}"
          TfArnBackendAccessRole: "{{ backend_access_role }}"
          TfArnSameAccountExecRole: "{{ same_account_exec_role }}"
          TfArnExecRole0001: "{{ account_0001_exec_role }}"
        termination_protection: yes
        tags:
          "{{ org_prefix }}:source": ansible
          "{{ org_prefix }}:namespace": "{{ org_prefix }}"
          "{{ org_prefix }}:purpose": "noninteractive"
          "{{ org_prefix }}:prefix": "{{ stack_prefix }}"

    - name: Stack for IAM user to use Terraform from Azure DevOps
      amazon.aws.cloudformation:
        stack_name: "{{ org_prefix }}-{{ stack_prefix }}-ado-user"
        region: us-east-1
        state: "present"
        template: "../cloudformation/managing-account/tf-identity/cfn-tf-access-user.yml"
        template_parameters:
          Prefix: "{{ org_prefix }}-{{ stack_prefix }}"
          TfAccessGroup: "{{ iam_group.stack_outputs.TfAccessGroup }}"
          UserName: ado
        termination_protection: yes
        tags:
          "{{ org_prefix }}:source": ansible
          "{{ org_prefix }}:namespace": "{{ org_prefix }}"
          "{{ org_prefix }}:purpose": "noninteractive"
          "{{ org_prefix }}:prefix": "{{ stack_prefix }}"
