AWSTemplateFormatVersion: "2010-09-09"
Description: |
  Terraform state locking

Parameters:
  KmsKeyArn:
    Type: String
    Description: The ARN of the KMS customer-managed key
  Prefix:
    Type: String
    Description: The prefix for AWS resource names

Resources:
  TfBackendDynamoDbTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: !Sub ${Prefix}-lock-${AWS::Region}
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      AttributeDefinitions:
        - AttributeName: LockID
          AttributeType: S
      KeySchema:
        - AttributeName: LockID
          KeyType: HASH
      SSESpecification:
        SSEEnabled: true
        KMSMasterKeyId: !Ref KmsKeyArn
        SSEType: KMS

Outputs:
  TfBackendDynamoDbTable:
    Value: !GetAtt TfBackendDynamoDbTable.Arn
    Export:
      Name: !Sub "${AWS::StackName}-ddb-arn"
